### ISSUE TITLE
Analysis and Design of Delfin Metric streaming requirement

### ISSUE THREAD

**Issue by NajmudheenCT** [sodafoundation/architecture-analysis#112]
**Issue/Feature Description:**
Bring out a design proposal for delfin. Framework hould be able to handle millions of metric within the collection time period 
**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Moving to TODO as the task is put on hold.
